/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Alien.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null} position={[-1.4,-2, 0]} scale={[0.01, 0.01, 0.01]}>
      <primitive object={nodes.root} />
      <primitive object={nodes.Bone023} />
      <skinnedMesh
        geometry={nodes['Alien-Animal_PostProcessing'].geometry}
        material={materials['Body-Alien-Animal']}
        skeleton={nodes['Alien-Animal_PostProcessing'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['Alien-Animal_Texturetest'].geometry}
        material={materials['postprocessing textures']}
        skeleton={nodes['Alien-Animal_Texturetest'].skeleton}
      />
      <skinnedMesh
        geometry={nodes.Cube001.geometry}
        material={materials['Red-Eye-Alien-Animal']}
        skeleton={nodes.Cube001.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Cube001_1.geometry}
        material={materials['Eye-Alien-Animal']}
        skeleton={nodes.Cube001_1.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Cube002.geometry}
        material={materials['Saliva-Alien-Animal']}
        skeleton={nodes.Cube002.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Cube002_1.geometry}
        material={materials['Red-Saliva-Alien-Animal']}
        skeleton={nodes.Cube002_1.skeleton}
      />
      <mesh geometry={nodes.Plane.geometry} material={materials.Ground} scale={[75.41, 75.41, 75.41]} />
    </group>
  )
}

useGLTF.preload('/Alien.gltf')
