/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from 'react-three-fiber';

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/chair.gltf')
  const { actions } = useAnimations(animations, group)
 

  

  useFrame(() => {
    group.current.rotation.y += 0.01;
  });
  return (
    <group ref={group} {...props} dispose={null} position={[-1.4,-2, 0]}  scale={[4,4,4]}>
      <mesh geometry={nodes.koltuk.geometry} material={materials.chair} position={[0, 0, 0]} rotation={[0, 2, 0]} />
    </group>
  )
}

useGLTF.preload('/chair.gltf')
