/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

import { useFrame } from 'react-three-fiber';

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Divanetto.gltf')
  const { actions } = useAnimations(animations, group)
 

  

  useFrame(() => {
    group.current.rotation.y += 0.01;
  });
  return (
    <group ref={group} {...props} dispose={null} position={[-0.4,-2, 0]} scale={[0.1, 0.1, 0.1]}>
      <mesh geometry={nodes.Knit001.geometry} material={nodes.Knit001.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Planks.geometry} material={nodes.Planks.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes.Fiber_wood032.geometry}
        material={nodes.Fiber_wood032.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Fiber_wood15.geometry}
        material={nodes.Fiber_wood15.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Fiber_wood06.geometry}
        material={nodes.Fiber_wood06.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Fiber_wood034.geometry}
        material={nodes.Fiber_wood034.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Fiber_wood033.geometry}
        material={nodes.Fiber_wood033.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Fiber_wood030.geometry}
        material={nodes.Fiber_wood030.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Fiber_wood031.geometry}
        material={nodes.Fiber_wood031.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Fiber_wood028.geometry}
        material={nodes.Fiber_wood028.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Fiber_wood026.geometry}
        material={nodes.Fiber_wood026.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Fiber_wood025.geometry}
        material={nodes.Fiber_wood025.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Fiber_wood029.geometry}
        material={nodes.Fiber_wood029.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Fiber_wood027.geometry}
        material={nodes.Fiber_wood027.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Fiber_wood022.geometry}
        material={nodes.Fiber_wood022.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Fiber_wood024.geometry}
        material={nodes.Fiber_wood024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Fiber_wood023.geometry}
        material={nodes.Fiber_wood023.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Fiber_wood021.geometry}
        material={nodes.Fiber_wood021.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Fiber_wood020.geometry}
        material={nodes.Fiber_wood020.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Fiber_wood019.geometry}
        material={nodes.Fiber_wood019.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Pattern_Chesterfield.geometry}
        material={nodes.Pattern_Chesterfield.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Chester.geometry} material={nodes.Chester.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Pillow001.geometry} material={nodes.Pillow001.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Pillow002.geometry} material={nodes.Pillow002.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Pillow003.geometry} material={nodes.Pillow003.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.knot001.geometry} material={nodes.knot001.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Knot002.geometry} material={nodes.Knot002.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rooot001.geometry} material={nodes.Rooot001.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Root002.geometry} material={nodes.Root002.material} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/Divanetto.gltf')
