/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

import { useFrame } from 'react-three-fiber';

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/IronMan.gltf')
  const { actions } = useAnimations(animations, group)
 

  

  useFrame(() => {
    group.current.rotation.y += 0.01;
  });
  return (
    <group ref={group} {...props} dispose={null}  position={[-1.4,-2, 0]} scale={[2, 2, 2]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={[0.01, 0.01, 0.01]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group position={[0, 122.28, 0.94]} scale={[115.76, 116.93, 116.93]}>
              <mesh geometry={nodes.Iron_Man_Mark_7_ArcReactor_0.geometry} material={materials['ArcReactor.001']} />
              <mesh geometry={nodes.Iron_Man_Mark_7_Black_0.geometry} material={materials['Black.001']} />
              <mesh geometry={nodes.Iron_Man_Mark_7_Blue_0.geometry} material={materials.Eyes} />
              <mesh geometry={nodes.Iron_Man_Mark_7_Eyes_0.geometry} material={materials['Eyes.001']} />
              <mesh geometry={nodes.Iron_Man_Mark_7_Glass_0.geometry} material={materials['Glass.001']} />
              <mesh geometry={nodes.Iron_Man_Mark_7_Gold_0.geometry} material={materials['Gold.001']} />
              <mesh geometry={nodes.Iron_Man_Mark_7_Red_0.geometry} material={nodes.Iron_Man_Mark_7_Red_0.material} />
              <mesh
                geometry={nodes.Iron_Man_Mark_7_Red_0001.geometry}
                material={nodes.Iron_Man_Mark_7_Red_0001.material}
              />
              <mesh geometry={nodes.Iron_Man_Mark_7_Repulsor_0.geometry} material={materials['Repulsor.001']} />
              <mesh geometry={nodes.Iron_Man_Mark_7_Silver_0.geometry} material={materials['Silver.001']} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/IronMan2.gltf')
