/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from 'react-three-fiber';
export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations  } = useGLTF('/Mario.gltf')
  const { actions } = useAnimations(animations, group)
  useFrame(() => {
    group.current.rotation.y += 0.01;
  });
  return (
    <group ref={group} {...props} dispose={null} position={[-1.4,-1, 0]} scale={[0.04, 0.04, 0.04]}>
      <mesh
        geometry={nodes.mario_obj.geometry}
        material={materials.mario_1}
        position={[0, 60.96, -22.75]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/Mario.gltf')
