/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'

import { useGLTF, useAnimations } from '@react-three/drei'

import { useFrame } from 'react-three-fiber';
export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Mickey.gltf')

  const { actions } = useAnimations(animations, group)
 

  

  useFrame(() => {
    group.current.rotation.y += 0.01;
  });
  return (
    <group ref={group} {...props} dispose={null} position={[-1.4,-2, 0]} scale={[0.03, 0.03, 0.03]}>
      <mesh geometry={nodes.Mickey_Mouse.geometry} material={materials['default']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/Mickey.gltf')
