/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from 'react-three-fiber';
export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/ontas.gltf')
  const { actions } = useAnimations(animations, group)
  useFrame(() => {
    group.current.rotation.y += 0.01;
  });
  return (
    <group ref={group} {...props} dispose={null} position={[-1.4,-1, 0]} scale={[3, 3, 3]}>
      <group position={[0, 0.05, -0.02]} >
        <group position={[0, 1.01, -0.06]} rotation={[-1.78, -0.82, -2.24]} />
      </group>
      <mesh
        geometry={nodes.Mesh001.geometry}
        material={materials.rock_mat_3}
        position={[0.01, 0.13, -0.04]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.Mesh002.geometry}
        material={nodes.Mesh002.material}
        position={[0.01, 0.13, -0.04]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.Mesh003.geometry}
        material={nodes.Mesh003.material}
        position={[0.01, 0.13, -0.04]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.Mesh004.geometry}
        material={nodes.Mesh004.material}
        position={[0.01, 0.13, -0.04]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.Mesh005.geometry}
        material={nodes.Mesh005.material}
        position={[0.01, 0.13, -0.04]}
        scale={[0.01, 0.01, 0.01]}
      />
    </group>
  )
}

useGLTF.preload('/ontas.gltf')
