/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

import { useFrame } from 'react-three-fiber';

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/SediaUfficio.gltf')
  const { actions } = useAnimations(animations, group)
 

  

  useFrame(() => {
    group.current.rotation.y += 0.01;
  });
  return (
    <group ref={group} {...props} dispose={null} position={[-1.4,-4.8, 0]} scale={[4.8, 4.8, 4.8]}>
      <group position={[0, 0.46, 0]} rotation={[-3.12, 1.14, -3.14]} scale={[0.01, 0.01, 0.01]}>
        <mesh geometry={nodes.Box015.geometry} material={nodes.Box015.material} position={[-267.26, 0.72, 102.36]} />
        <group position={[-267.26, 0.72, 102.36]}>
          <mesh geometry={nodes.Mesh011.geometry} material={nodes.Mesh011.material} />
          <mesh geometry={nodes.Mesh011_1.geometry} material={nodes.Mesh011_1.material} />
        </group>
        <mesh
          geometry={nodes.Cylinder003.geometry}
          material={nodes.Cylinder003.material}
          position={[-267.26, 0.72, 102.36]}
        />
        <mesh
          geometry={nodes.Cylinder006.geometry}
          material={nodes.Cylinder006.material}
          position={[-267.26, 0.72, 102.36]}
        />
        <mesh
          geometry={nodes.Cylinder007.geometry}
          material={nodes.Cylinder007.material}
          position={[-267.26, 0.72, 102.36]}
        />
        <mesh geometry={nodes.Line011.geometry} material={nodes.Line011.material} position={[-267.26, 0.72, 102.36]} />
        <mesh geometry={nodes.Line012.geometry} material={nodes.Line012.material} position={[-267.26, 0.72, 102.36]} />
        <mesh geometry={nodes.Line013.geometry} material={nodes.Line013.material} position={[-267.26, 0.72, 102.36]} />
        <mesh geometry={nodes.Line014.geometry} material={nodes.Line014.material} position={[-267.26, 0.72, 102.36]} />
        <mesh
          geometry={nodes.Object003.geometry}
          material={nodes.Object003.material}
          position={[-267.26, 0.72, 102.36]}
        />
        <mesh
          geometry={nodes.Rectangle002.geometry}
          material={nodes.Rectangle002.material}
          position={[-267.26, 0.72, 102.36]}
        />
        <mesh
          geometry={nodes.Rectangle003.geometry}
          material={nodes.Rectangle003.material}
          position={[-267.26, 0.72, 102.36]}
        />
        <mesh geometry={nodes.Shape.geometry} material={nodes.Shape.material} position={[-267.26, 0.72, 102.36]} />
      </group>
    </group>
  )
}

useGLTF.preload('/SediaUfficio.gltf')
