/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

import { useFrame } from 'react-three-fiber';

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/TeleCamera.gltf')
  const { actions } = useAnimations(animations, group)
 

  

  useFrame(() => {
    group.current.rotation.y += 0.01;
  });
  return (
    <group ref={group} {...props} dispose={null} position={[-1.4,0, 0]} scale={[4, 4, 4]}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <primitive object={nodes.Top} />
        <skinnedMesh
          geometry={nodes.Mesh.geometry}
          material={materials['Standard.003']}
          skeleton={nodes.Mesh.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/TeleCameragltf.gltf')
