/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

import { useFrame } from 'react-three-fiber';
export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/troll.gltf')
  const { actions } = useAnimations(animations, group)
 

  

  useFrame(() => {
    group.current.rotation.y += 0.01;
  });
  return (
    <group ref={group} {...props} dispose={null} position={[-1.4,0, 0]}>
      <group name="Hips" scale={[0.07, 0.07, 0.07]}>
        <primitive object={nodes.Hips_1} />
        <skinnedMesh
          geometry={nodes.Mesh023.geometry}
          material={materials['07 - Default.001']}
          skeleton={nodes.Mesh023.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Mesh023_1.geometry}
          material={materials['14 - Dsadds.001']}
          skeleton={nodes.Mesh023_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Mesh023_2.geometry}
          material={materials['14 - Defaf.001']}
          skeleton={nodes.Mesh023_2.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/troll.gltf')
