/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from 'react-three-fiber';
export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Warrior.gltf')
  const { actions } = useAnimations(animations, group)

  useFrame(() => {
    group.current.rotation.y += 0.01;
  });
  
  return (
    <group ref={group} {...props} dispose={null} position={[-1.4,-1, 0]} scale={[2.4, 2.4, 2.4]}>
      <group name="warrior_rigging_MAIN_Inner_Ctrl001" >
        <group name="warrior_rigging_l_Arm_ScaleGrp001" position={[15.37, 11.96, -126.73]} rotation={[-1.62, 0, 1.54]}>
          <group
            name="warrior_rigging_l_Arm_WristFk_CtrlGrp001"
            position={[-26.84, -24.12, 15.45]}
            rotation={[-1.68, -0.48, -2.55]}>
            <group name="warrior_rigging_l_Arm_WristFk_Ctrl001" />
          </group>
        </group>
      </group>
      <group name="warrior_rigging" rotation={[Math.PI / 2, 0, 6]} scale={[0.01, 0.01, 0.01]}>
        <group name="warrior_rigging_SHJntGrp">
          <primitive object={nodes.warrior_rigging_ROOTSHJnt} />
          <skinnedMesh
            name="warrior_lowpolywarrior3dmodel"
            geometry={nodes.warrior_lowpolywarrior3dmodel.geometry}
            material={nodes.warrior_lowpolywarrior3dmodel.material}
            skeleton={nodes.warrior_lowpolywarrior3dmodel.skeleton}
            morphTargetDictionary={nodes.warrior_lowpolywarrior3dmodel.morphTargetDictionary}
            morphTargetInfluences={nodes.warrior_lowpolywarrior3dmodel.morphTargetInfluences}
          />
        </group>
        <group name="warrior_rigging_MAIN_Offset_Ctrl">
          <group name="warrior_rigging_MAIN_Ctrl">
            <group name="warrior_rigging_MAIN_Inner_Ctrl">
              <group
                name="warrior_rigging_l_Arm_ScaleGrp"
                position={[15.37, 11.96, -126.73]}
                rotation={[-1.62, 0, 1.54]}>
                <group
                  name="warrior_rigging_l_Arm_WristFk_CtrlGrp"
                  position={[-26.84, -24.12, 15.45]}
                  rotation={[-1.68, -0.48, -2.55]}>
                  <group name="warrior_rigging_l_Arm_WristFk_Ctrl" rotation={[-0.58, 0, 0.51]}>
                    <group
                      name="Locator_sword"
                      position={[5.12, -0.19, 1.56]}
                      rotation={[-1.5, -0.51, -1.62]}
                      scale={[6, 6, 6]}>
                      <mesh
                        geometry={nodes.sword_lowpolysword.geometry}
                        material={nodes.sword_lowpolysword.material}
                        scale={[0.17, 0.17, 0.17]}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
      <mesh
        geometry={nodes.Stage.geometry}
        material={materials['lambert1.002']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.grass.geometry}
        material={materials['Grass.002']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
    </group>
  )
}

useGLTF.preload('/Warrior.gltf')
